lfads_file_server: 205.208.22.225
lfads_dir_path: ~/peter/lfads_analysis/data/model_output/
lfads_run_names: ['fit_direction_Transient_posture_serial_2targ'] #['kl_co_dim_search', 'split_rockstar_1000ms200ms_overlap']
username: macleanlab

# order will be preserved in lfads yaml file
datasets:
  rockstar: 
    name: RS
    raw: pmalonis@cri-syncmon.cri.uchicago.edu:/gpfs/data/nicho-lab/pmalonis/data/raw/rockstar.mat
    adhoc_param: autolfads-split-trunc-02 #kl-co-dim-search-FDCWrX-offset
  mack:
    name: MK
    raw: pmalonis@cri-syncmon.cri.uchicago.edu:/gpfs/data/nicho-lab/pmalonis/data/raw/mack.mat
    adhoc_param: kl-co-dim-search-FDCWrX-offset
  raju-M1-no-bad-trials:
    name: RJ
    raw: pmalonis@cri-syncmon.cri.uchicago.edu:/gpfs/data/nicho-lab/pmalonis/data/raw/raju-M1-no-bad-trials.mat
    adhoc_param: kl-co-dim-search-6p5E8J-offset
  fit-direction-Transient-posture-serial-2targ:
    name: RNN
    raw: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/raw/fit-direction-Transient-posture-serial-2targ.raw
    adhoc_param: kl-co-dim-search-6p5E8J-offset

data_chunking:
  chunk_length: 0.6
  overlap: 0.2

truncate_autolfads_chunks: True

autolfads_time_bin: 0.01

selection_metric: adhoc

target_preprocessing_search:
  fit_direction: [True, False]
  reference: ['hand','shoulder']
  corr: ['ca']
  poly_features: [False]
  reduce_time: [False]
  use_rates: [False]
  reduce_neurons: [False]
  filter_co: [False]
  win_lim: ['(0,0.25)','(0.05,0.3)','(0.10,0.35)','(0.15,0.4)']
  hand_time: [0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4]
  rate_pcs: [2]

#submovement transitions
firstmove_speed_transition_thresh: 1000
firstmove_min_speed_prominence: 25
firstmove_min_distance: 200

correction_speed_transition_thresh: 1000
correction_min_speed_prominence: 25
correction_min_distance: 200

speed_filter_win: 101
speed_filter_order: 2

angle_win: 50 #half-length of window (in ms) to compute angle around speed local minimum 
angle_threshold: 15 # angle threshold (in degrees) to count as a submovement, if 
                    # prominence criterion not met 

right_prominence_ratio: 5
left_prominence_thresh: 10
exclude_movement_post_target_win: 50

accel_thresh: 0.5 # threshold for acceleration phase timing 

roc_bootstrap_repeats: 200
background_subsample: 0.05 
roc_ci_alpha: 0.05

neural_offset: 0.05
# speed_transition_thresh: 100
# min_speed_prominence: 100
# min_distance: 0

center_out:
  rockstar: pmalonis@205.208.57.121:~/center_out/rs1050225_clean_SNRgt4.mat

integration_win_size: 0.2
peri_target_kinematics_start: -0.1
peri_target_kinematics_stop: 0
post_peak_win: 0.15
post_target_win_start: 0.05
post_target_win_stop: 0.3
min_peak_spacing: 5 #minimum time, in 10s of ms, between peaks of controller output to count peak (as fed to scipy findpeaks)
target_decoding_smoothed_control_std: 10
#kinematic decoding
rate_sigma_kin_decoding: 25 #sigma of smoothing kernel for decoding kinematics from firing rate
kin_decoding_cv_splits: 5
rate_sigma_example_plot: 25

target_prediction_cv_splits: 5
total_train_test_split_ratio: 0.5

significance_cv_repeats: 10
significance_cv_folds: 10

split_random_state: 1217

random_forest_random_state: 1748

preprocess:
  cutoff: 20
  filter_order: 3
  post_trial_pad: 0.5
  win_size: 25

#arguments to src/utils.contrasting_colors for each plot
colors:
  controller_example:
    start_hue: 0
    reverse: True
  window_performance:
    start_hue: 0.3
    saturation: 1.0
  correction_decode:
    start_hue: 0.38
    saturation: 0.9
    hue_change: 1.5
    reverse: True
  target_vs_firstmove:
    start_hue: 0.12
    saturation: 0.7
    reverse: True

event_split_ratio: 0.2

window_compare_length: 0.25

target_auc_win_lims: ['(-0.3,-0.2)', '(-0.25,-0.15)',
             '(-0.2,-0.1)','(-0.15,-0.05)','(-0.1,0.0)',
             '(-0.05,0.05)','(0,0.1)','(0.05,0.15)', '(0.10,0.2)',
             '(0.15,0.25)', '(0.2,0.3)', '(0.25,0.35)','(0.3,0.4)']


movement_auc_win_lims: ['(-0.4,-0.3)','(-0.35,-0.25)','(-0.3,-0.2)', '(-0.25,-0.15)',
              '(-0.2,-0.1)','(-0.15,-0.05)','(-0.1,0.0)',
             '(-0.05,0.05)','(0,0.1)','(0.05,0.15)', '(0.10,0.2)',
             '(0.15,0.25)', '(0.2,0.3)', '(0.25,0.35)','(0.3,0.4)']

#correlation analysis
firstmove_win_start: -0.3
firstmove_win_stop: 0
correction_win_start: -0.3 
correction_win_stop: 0
maximum_win_start: -0.15
maximum_win_stop: 0.15

#targets
# target_preprocessing_search:
#   fit_direction: [True, False]
#   reference: ['hand','shoulder']
#   corr: ['ca']
#   poly_features: [False]
#   reduce_time: [False]
#   use_rates: [False]
#   reduce_neurons: [False]
#   filter_co: [False]
#   win_lim: ['(-0.3,-0.05)', '(-0.25,-0.0)',
#              '(-0.2,0.05)','(-0.15,0.1)','(-0.1,0.15)',
#              '(-0.05,0.2)','(0,0.25)','(0.05,0.3)','(0.10,0.35)',
#              '(0.15,0.4)']
#   hand_time: [-0.3, -0.25, -0.2, -0.15, -0.1, -0.05, 0, 0.05, 
#               0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4]
#   rate_pcs: [2]

#raju new params
# target_preprocessing_search:
#   fit_direction: [True, False]
#   reference: ['hand','shoulder']
#   corr: ['ca']
#   poly_features: [False]
#   reduce_time: [False]
#   use_rates: [False]
#   reduce_neurons: [False]
#   filter_co: [False]
#   win_lim: ['(0,0.25)','(0.05,0.3)','(0.10,0.35)',
#             '(0.15,0.4)']
#   hand_time: [0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4]
#   rate_pcs: [2]

svr_parameters: 
  kernel: ['rbf']
  gamma: ['scale']
  C: [0.1, 0.3, 0.5, 0.7, 0.9,1.1,1.3, 1.5]

random_forest_parameters: 
  max_features: ['auto', 'sqrt', 'log2']
  min_samples_leaf: [1,5,10,15]

num_cpus: 48

rate_pcs_search_min: 2
rate_pcs_search_max: 20