datasets:
  raju:
    inputInfo: macleanlab@205.208.22.226:~/peter/lfads_analysis/data/raw//raju.mat
    params:
      1f~2d~:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_1f_2d_/single_raju/lfadsOutput/model_runs_raju.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_1f_2d_/single_raju/lfadsOutput/model_runs_raju.h5_valid_posterior_sample_and_average
      2NJ~T3:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_2NJ_T3/single_raju/lfadsOutput/model_runs_raju.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_2NJ_T3/single_raju/lfadsOutput/model_runs_raju.h5_valid_posterior_sample_and_average
      3CLTSo:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_3CLTSo/single_raju/lfadsOutput/model_runs_raju.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_3CLTSo/single_raju/lfadsOutput/model_runs_raju.h5_valid_posterior_sample_and_average
      6zH8vI:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_6zH8vI/single_raju/lfadsOutput/model_runs_raju.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_6zH8vI/single_raju/lfadsOutput/model_runs_raju.h5_valid_posterior_sample_and_average
      8QTVEk:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_8QTVEk/single_raju/lfadsOutput/model_runs_raju.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_8QTVEk/single_raju/lfadsOutput/model_runs_raju.h5_valid_posterior_sample_and_average
      Ud-Q0k:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_Ud-Q0k/single_raju/lfadsOutput/model_runs_raju.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_Ud-Q0k/single_raju/lfadsOutput/model_runs_raju.h5_valid_posterior_sample_and_average
      dFpZUD:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_dFpZUD/single_raju/lfadsOutput/model_runs_raju.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_dFpZUD/single_raju/lfadsOutput/model_runs_raju.h5_valid_posterior_sample_and_average
      g42h9j:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_g42h9j/single_raju/lfadsOutput/model_runs_raju.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_g42h9j/single_raju/lfadsOutput/model_runs_raju.h5_valid_posterior_sample_and_average
    raw: macleanlab@205.208.22.226:~/peter/lfads_analysis/data/raw//raju.mat
  raju_M1:
    inputInfo: macleanlab@205.208.22.226:~/peter/lfads_analysis/data/raw//raju_M1.mat
    params:
      1f~2d~:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_1f_2d_/single_raju_M1/lfadsOutput/model_runs_raju_M1.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_1f_2d_/single_raju_M1/lfadsOutput/model_runs_raju_M1.h5_valid_posterior_sample_and_average
      2NJ~T3:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_2NJ_T3/single_raju_M1/lfadsOutput/model_runs_raju_M1.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_2NJ_T3/single_raju_M1/lfadsOutput/model_runs_raju_M1.h5_valid_posterior_sample_and_average
      3CLTSo:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_3CLTSo/single_raju_M1/lfadsOutput/model_runs_raju_M1.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_3CLTSo/single_raju_M1/lfadsOutput/model_runs_raju_M1.h5_valid_posterior_sample_and_average
      6zH8vI:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_6zH8vI/single_raju_M1/lfadsOutput/model_runs_raju_M1.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_6zH8vI/single_raju_M1/lfadsOutput/model_runs_raju_M1.h5_valid_posterior_sample_and_average
      8QTVEk:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_8QTVEk/single_raju_M1/lfadsOutput/model_runs_raju_M1.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_8QTVEk/single_raju_M1/lfadsOutput/model_runs_raju_M1.h5_valid_posterior_sample_and_average
      Ud-Q0k:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_Ud-Q0k/single_raju_M1/lfadsOutput/model_runs_raju_M1.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_Ud-Q0k/single_raju_M1/lfadsOutput/model_runs_raju_M1.h5_valid_posterior_sample_and_average
      dFpZUD:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_dFpZUD/single_raju_M1/lfadsOutput/model_runs_raju_M1.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_dFpZUD/single_raju_M1/lfadsOutput/model_runs_raju_M1.h5_valid_posterior_sample_and_average
      g42h9j:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_g42h9j/single_raju_M1/lfadsOutput/model_runs_raju_M1.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_g42h9j/single_raju_M1/lfadsOutput/model_runs_raju_M1.h5_valid_posterior_sample_and_average
    raw: macleanlab@205.208.22.226:~/peter/lfads_analysis/data/raw//raju_M1.mat
  raju_PMd:
    inputInfo: macleanlab@205.208.22.226:~/peter/lfads_analysis/data/raw//raju_PMd.mat
    params:
      1f~2d~:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_1f_2d_/single_raju_PMd/lfadsOutput/model_runs_raju_PMd.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_1f_2d_/single_raju_PMd/lfadsOutput/model_runs_raju_PMd.h5_valid_posterior_sample_and_average
      2NJ~T3:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_2NJ_T3/single_raju_PMd/lfadsOutput/model_runs_raju_PMd.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_2NJ_T3/single_raju_PMd/lfadsOutput/model_runs_raju_PMd.h5_valid_posterior_sample_and_average
      3CLTSo:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_3CLTSo/single_raju_PMd/lfadsOutput/model_runs_raju_PMd.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_3CLTSo/single_raju_PMd/lfadsOutput/model_runs_raju_PMd.h5_valid_posterior_sample_and_average
      6zH8vI:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_6zH8vI/single_raju_PMd/lfadsOutput/model_runs_raju_PMd.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_6zH8vI/single_raju_PMd/lfadsOutput/model_runs_raju_PMd.h5_valid_posterior_sample_and_average
      8QTVEk:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_8QTVEk/single_raju_PMd/lfadsOutput/model_runs_raju_PMd.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_8QTVEk/single_raju_PMd/lfadsOutput/model_runs_raju_PMd.h5_valid_posterior_sample_and_average
      Ud-Q0k:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_Ud-Q0k/single_raju_PMd/lfadsOutput/model_runs_raju_PMd.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_Ud-Q0k/single_raju_PMd/lfadsOutput/model_runs_raju_PMd.h5_valid_posterior_sample_and_average
      dFpZUD:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_dFpZUD/single_raju_PMd/lfadsOutput/model_runs_raju_PMd.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_dFpZUD/single_raju_PMd/lfadsOutput/model_runs_raju_PMd.h5_valid_posterior_sample_and_average
      g42h9j:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_g42h9j/single_raju_PMd/lfadsOutput/model_runs_raju_PMd.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_g42h9j/single_raju_PMd/lfadsOutput/model_runs_raju_PMd.h5_valid_posterior_sample_and_average
    raw: macleanlab@205.208.22.226:~/peter/lfads_analysis/data/raw//raju_PMd.mat
  rockstar:
    inputInfo: macleanlab@205.208.22.226:~/peter/lfads_analysis/data/raw//rockstar.mat
    params:
      1f~2d~:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_1f_2d_/single_rockstar/lfadsOutput/model_runs_rockstar.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_1f_2d_/single_rockstar/lfadsOutput/model_runs_rockstar.h5_valid_posterior_sample_and_average
      2NJ~T3:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_2NJ_T3/single_rockstar/lfadsOutput/model_runs_rockstar.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_2NJ_T3/single_rockstar/lfadsOutput/model_runs_rockstar.h5_valid_posterior_sample_and_average
      3CLTSo:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_3CLTSo/single_rockstar/lfadsOutput/model_runs_rockstar.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_3CLTSo/single_rockstar/lfadsOutput/model_runs_rockstar.h5_valid_posterior_sample_and_average
      6zH8vI:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_6zH8vI/single_rockstar/lfadsOutput/model_runs_rockstar.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_6zH8vI/single_rockstar/lfadsOutput/model_runs_rockstar.h5_valid_posterior_sample_and_average
      8QTVEk:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_8QTVEk/single_rockstar/lfadsOutput/model_runs_rockstar.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_8QTVEk/single_rockstar/lfadsOutput/model_runs_rockstar.h5_valid_posterior_sample_and_average
      Ud-Q0k:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_Ud-Q0k/single_rockstar/lfadsOutput/model_runs_rockstar.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_Ud-Q0k/single_rockstar/lfadsOutput/model_runs_rockstar.h5_valid_posterior_sample_and_average
      dFpZUD:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_dFpZUD/single_rockstar/lfadsOutput/model_runs_rockstar.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_dFpZUD/single_rockstar/lfadsOutput/model_runs_rockstar.h5_valid_posterior_sample_and_average
      g42h9j:
        train: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_g42h9j/single_rockstar/lfadsOutput/model_runs_rockstar.h5_train_posterior_sample_and_average
        valid: macleanlab@205.208.22.225:~/peter/lfads_analysis/data/model_output/controller_params_sweep/param_g42h9j/single_rockstar/lfadsOutput/model_runs_rockstar.h5_valid_posterior_sample_and_average
    raw: macleanlab@205.208.22.226:~/peter/lfads_analysis/data/raw//rockstar.mat
integration_win_size: 0.2
peri_target_kinematics_start: -0.1
peri_target_kinematics_stop: 0
post_target_win_start: 0.05
post_target_win_stop: 0.3
preprocess:
  cutoff: 20
  filter_order: 3
  post_trial_pad: 0.5
  win_size: 25
username: pmalonis
