align_peaks: true
center_out:
  rockstar: pmalonis@205.208.57.121:~/center_out/rs1050225_clean_SNRgt4.mat
integration_win_size: 0.2
peri_target_kinematics_start: -0.1
peri_target_kinematics_stop: 0
post_peak_win: 0.15
post_target_win_start: 0.05
post_target_win_stop: 0.3
min_peak_spacing: 5 #minimum time, in ms, between peaks of controller output to count peak (as fed to scipy findpeaks)
target_prediction_cv_splits: 5
target_decoding_smoothed_control_std: 10
#kinematic decoding
rate_sigma_kin_decoding: 25 #sigma of smoothing kernel for decoding kinematics from firing rate
kin_decoding_cv_splits: 5

preprocess:
  cutoff: 20
  filter_order: 3
  post_trial_pad: 0.5
  win_size: 25

lfads_file_server: cri-syncmon.cri.uchicago.edu
lfads_dir_path: /gpfs/data/nicho-lab/pmalonis/data/model_output/
username: pmalonis
#lfads_file_pattern: */*/*/*/model_runs_*.h5*_posterior_sample_and_average # will work for other patterns as long as first wildcard corresponds to the dataset and the second is "train" or "valid"

raw_datasets:
  rockstar: pmalonis@cri-syncmon.cri.uchicago.edu:/gpfs/data/nicho-lab/pmalonis/data/raw/rockstar.mat
  raju: pmalonis@cri-syncmon.cri.uchicago.edu:/gpfs/data/nicho-lab/pmalonis/data/raw/raju.mat
  mack: pmalonis@cri-syncmon.cri.uchicago.edu:/gpfs/data/nicho-lab/pmalonis/data/raw/mack.mat