name: lfads_analysis
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - astropy
  - h5py
  - matplotlib
  - numpy=1.18.1
  - pandas
  - python=3.6.10
  - scikit-learn
  - scipy
  - seaborn
  - snakemake
  - yaml
  - pip:
    - ray